# I am writing this code to practice working with pdf to df conversion and then using pandas on it

In [6]:
import tabula
import pandas as pd

In [4]:
tabula.convert_into("Mids D-Sheet CS.pdf","Mids D-Sheet CS.csv",output_format="csv",pages="all")

In [7]:
df = pd.read_csv("Mids D-Sheet CS.csv")
df.head()

,Date,Time,Class,Sec,ST,Course,Title,Instructor,Room,Cap.,Occ.,Block
0,Mon\r02-Nov-2026,08:30-09:50,BAE-5B,B,37,CSC325,Computer Organization and Assembly Language,Raja Rashid Mehmood,107,50,22,AB-II
1,Mon\r02-Nov-2026,08:30-09:50,BAE-5B,B,37,CSC325,Computer Organization and Assembly Language,Raja Rashid Mehmood,110,50,15,AB-II
2,Mon\r02-Nov-2026,08:30-09:50,BAI-2A,A,51,HUM120,Expository Writing,Mahnoor,106,50,25,AB-II
3,Mon\r02-Nov-2026,08:30-09:50,BAI-2A,A,51,HUM120,Expository Writing,Mahnoor,107,50,10,AB-II
4,Mon\r02-Nov-2026,08:30-09:50,BAI-2A,A,51,HUM120,Expository Writing,Mahnoor,108,46,16,AB-II

# My datesheet

In [ ]:
df = df[df['Class']=="BDS-7A"]
df

,Date,Time,Class,Sec,ST,Course,Title,Instructor,Room,Cap.,Occ.,Block
97,Mon\r02-Nov-2026,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,111,50,18,AB-II
98,Mon\r02-Nov-2026,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,G-07,70,35,AB-II
173,Tue\r03-Nov-2026,13:00-14:20,BDS-7A,A,1,DSC410,Cloud Computing,Qasim Malik,G-05,100,1,AB-II
190,Tue\r03-Nov-2026,14:30-15:50,BDS-7A,A,1,DSC413,Topics in Data Science,Qasim Malik,106,50,1,AB-II
214,Tue\r03-Nov-2026,16:00-17:20,BDS-7A,A,44,AIC365,Natural Language Processing,Anum Zehra,G-08,100,44,AB-II
271,Wed\r04-Nov-2026,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-05,100,5,AB-II
272,Wed\r04-Nov-2026,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-06,100,44,AB-II
273,Wed\r04-Nov-2026,11:30-12:50,BDS-7A,A,6,CSC325,Computer Organization & Assembly Language,Taimur Shahzad,G-06,100,6,AB-II
548,Fri 06-Nov-2026,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-07,70,14,AB-II
549,Fri 06-Nov-2026,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-08,100,50,AB-II
625,Sat\r07-Nov-2026,11:30-12:50,BDS-7A,A,35,AIC380,Artificial Neural Networks and Deep Learning,Dr. Zobia Rehman,G-06,100,2,AB-II
626,Sat\r07-Nov-2026,11:30-12:50,BDS-7A,A,35,AIC380,Artificial Neural Networks and Deep Learning,Dr. Zobia Rehman,G-07,70,33,AB-II
627,Sat\r07-Nov-2026,11:30-12:50,BDS-7A,A,1,CSC483,Topics in Computer Science II,Qasim Malik,105,46,1,AB-II

In [9]:
df["Date"] = pd.to_datetime(df["Date"])
df

,Date,Time,Class,Sec,ST,Course,Title,Instructor,Room,Cap.,Occ.,Block
97,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,111,50,18,AB-II
98,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,G-07,70,35,AB-II
173,2026-11-03,13:00-14:20,BDS-7A,A,1,DSC410,Cloud Computing,Qasim Malik,G-05,100,1,AB-II
190,2026-11-03,14:30-15:50,BDS-7A,A,1,DSC413,Topics in Data Science,Qasim Malik,106,50,1,AB-II
214,2026-11-03,16:00-17:20,BDS-7A,A,44,AIC365,Natural Language Processing,Anum Zehra,G-08,100,44,AB-II
271,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-05,100,5,AB-II
272,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-06,100,44,AB-II
273,2026-11-04,11:30-12:50,BDS-7A,A,6,CSC325,Computer Organization & Assembly Language,Taimur Shahzad,G-06,100,6,AB-II
548,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-07,70,14,AB-II
549,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-08,100,50,AB-II
625,2026-11-07,11:30-12:50,BDS-7A,A,35,AIC380,Artificial Neural Networks and Deep Learning,Dr. Zobia Rehman,G-06,100,2,AB-II
626,2026-11-07,11:30-12:50,BDS-7A,A,35,AIC380,Artificial Neural Networks and Deep Learning,Dr. Zobia Rehman,G-07,70,33,AB-II
627,2026-11-07,11:30-12:50,BDS-7A,A,1,CSC483,Topics in Computer Science II,Qasim Malik,105,46,1,AB-II

In [13]:
df["Day"] = df["Date"].dt.day_name()
df.drop(df[df["Title"]=="Artificial Neural Networks and Deep Learning"].index,inplace = True)
df

,Date,Time,Class,Sec,ST,Course,Title,Instructor,Room,Cap.,Occ.,Block,Day
97,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,111,50,18,AB-II,Monday
98,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,G-07,70,35,AB-II,Monday
173,2026-11-03,13:00-14:20,BDS-7A,A,1,DSC410,Cloud Computing,Qasim Malik,G-05,100,1,AB-II,Tuesday
190,2026-11-03,14:30-15:50,BDS-7A,A,1,DSC413,Topics in Data Science,Qasim Malik,106,50,1,AB-II,Tuesday
214,2026-11-03,16:00-17:20,BDS-7A,A,44,AIC365,Natural Language Processing,Anum Zehra,G-08,100,44,AB-II,Tuesday
271,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-05,100,5,AB-II,Wednesday
272,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-06,100,44,AB-II,Wednesday
273,2026-11-04,11:30-12:50,BDS-7A,A,6,CSC325,Computer Organization & Assembly Language,Taimur Shahzad,G-06,100,6,AB-II,Wednesday
548,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-07,70,14,AB-II,Friday
549,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-08,100,50,AB-II,Friday
627,2026-11-07,11:30-12:50,BDS-7A,A,1,CSC483,Topics in Computer Science II,Qasim Malik,105,46,1,AB-II,Saturday

In [18]:
df["Day"] = df["Date"].dt.day_name()
df.drop(df[df["Title"]=="Cloud Computing"].index,inplace = True)
df

,Date,Time,Class,Sec,ST,Course,Title,Instructor,Room,Cap.,Occ.,Block,Day
97,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,111,50,18,AB-II,Monday
98,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,G-07,70,35,AB-II,Monday
190,2026-11-03,14:30-15:50,BDS-7A,A,1,DSC413,Topics in Data Science,Qasim Malik,106,50,1,AB-II,Tuesday
214,2026-11-03,16:00-17:20,BDS-7A,A,44,AIC365,Natural Language Processing,Anum Zehra,G-08,100,44,AB-II,Tuesday
271,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-05,100,5,AB-II,Wednesday
272,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-06,100,44,AB-II,Wednesday
273,2026-11-04,11:30-12:50,BDS-7A,A,6,CSC325,Computer Organization & Assembly Language,Taimur Shahzad,G-06,100,6,AB-II,Wednesday
548,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-07,70,14,AB-II,Friday
549,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-08,100,50,AB-II,Friday

In [19]:
df["Day"] = df["Date"].dt.day_name()
df.drop(df[df["Title"]=="Topics in Computer Science II	"].index,inplace = True)
df

,Date,Time,Class,Sec,ST,Course,Title,Instructor,Room,Cap.,Occ.,Block,Day
97,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,111,50,18,AB-II,Monday
98,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,G-07,70,35,AB-II,Monday
190,2026-11-03,14:30-15:50,BDS-7A,A,1,DSC413,Topics in Data Science,Qasim Malik,106,50,1,AB-II,Tuesday
214,2026-11-03,16:00-17:20,BDS-7A,A,44,AIC365,Natural Language Processing,Anum Zehra,G-08,100,44,AB-II,Tuesday
271,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-05,100,5,AB-II,Wednesday
272,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-06,100,44,AB-II,Wednesday
273,2026-11-04,11:30-12:50,BDS-7A,A,6,CSC325,Computer Organization & Assembly Language,Taimur Shahzad,G-06,100,6,AB-II,Wednesday
548,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-07,70,14,AB-II,Friday
549,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-08,100,50,AB-II,Friday

In [20]:
df["Day"] = df["Date"].dt.day_name()
df.drop(df[df["Title"]=="Topics in Data Science"].index,inplace = True)
df

,Date,Time,Class,Sec,ST,Course,Title,Instructor,Room,Cap.,Occ.,Block,Day
97,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,111,50,18,AB-II,Monday
98,2026-11-02,16:00-17:20,BDS-7A,A,53,HUM121,Technical and Business Writing,Maria Khan,G-07,70,35,AB-II,Monday
214,2026-11-03,16:00-17:20,BDS-7A,A,44,AIC365,Natural Language Processing,Anum Zehra,G-08,100,44,AB-II,Tuesday
271,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-05,100,5,AB-II,Wednesday
272,2026-11-04,11:30-12:50,BDS-7A,A,49,CSC325,Computer Organization and Assembly Language,Taimur Shahzad,G-06,100,44,AB-II,Wednesday
273,2026-11-04,11:30-12:50,BDS-7A,A,6,CSC325,Computer Organization & Assembly Language,Taimur Shahzad,G-06,100,6,AB-II,Wednesday
548,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-07,70,14,AB-II,Friday
549,2026-11-06,14:30-15:50,BDS-7A,A,64,CSC418,DevOps for Cloud Computing,Qasim Malik,G-08,100,50,AB-II,Friday

In [26]:
df.to_html("mids_datesheet.html",index=False)